/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32l4_spi_driver.h"

int main(void)
{
    SPI1_Init();

    uint8_t tx = 0x55;
    uint8_t rx;

    while (1)
    {
        rx = SPI1_TransmitReceive(tx);
        for (volatile int i = 0; i < 100000; i++); // small delay
    }
}
