/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32l4xx_hal.h"
#include "tim.h"
#include "uart2.h"
#include "adc.h"
#include "uart1.h"

/* Function Prototypes */
void SystemInit(void);
void Error_Handler(void);
void SystemClock_Config(void);
void InitSPI1(void);

SPI_HandleTypeDef tSpi1;

uint8_t ucSpiTxBuff[] = "Hello STM32 SPI1 Module\r\n";
uint16_t uhTxBuffSize = sizeof(ucSpiTxBuff);
uint8_t ucSpiRxBuff[100];

/**
  * @brief  System Initialization
  * @param  None
  * @retval None
  */
void SystemInit(void)
{
    // Enable FPU if needed
    #if (__FPU_PRESENT == 1) && (__FPU_USED == 1)
    SCB->CPACR |= ((3UL << 10*2)|(3UL << 11*2));  /* set CP10 and CP11 Full Access */
    #endif
}

/**
  * @brief  This function is executed in case of error occurrence.
  * @param  None
  * @retval None
  */
void Error_Handler(void)
{
    __disable_irq();
    while (1)
    {
        // Add error indication here (LED blink, etc.)
        // For now, just reset the system
        NVIC_SystemReset();
    }
}

int main(void)
{
	uint8_t ucResBuff[100] = {0};
	uint16_t uhResSize = 0;
	/* Initialize HAL. */
	HAL_Init();

	SystemClock_Config();

	InitUart2();

	InitSPI1();

	HAL_SPI_TransmitReceive(&tSpi1, ucSpiTxBuff, ucSpiRxBuff, uhTxBuffSize, 100);

	/* Super loop. */
	while(1)
	{
		if(strcmp((char*)ucSpiTxBuff, (char*)ucSpiRxBuff) == 0)
		{
			uhResSize = sprintf((char*)ucResBuff, "SPI Worked ");
			memcpy(ucResBuff + uhResSize, ucSpiRxBuff, uhTxBuffSize);
			ucResBuff[uhResSize + uhTxBuffSize] = '\r';
			ucResBuff[uhResSize + uhTxBuffSize + 1] = '\n';

			uhResSize = (uhResSize + uhTxBuffSize + 2);
		}
		else
		{
			uhResSize = sprintf((char*)ucResBuff, "Hello STM32 SPI1 Module\r\n");
		}

		Uart2TxData(ucResBuff, uhResSize);
		HAL_Delay(500);
	}
}

void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    // Configure the main internal regulator output voltage
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    // Initializes the CPU, AHB and APB busses clocks
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM = 1;
    RCC_OscInitStruct.PLL.PLLN = 10;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV7;
    RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
    RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        Error_Handler();
    }

    // Initializes the CPU, AHB and APB busses clocks
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                                |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK) {
        Error_Handler();
    }
}

void InitSPI1(void)
{
	GPIO_InitTypeDef tSPIGpio = {0};

	__HAL_RCC_SPI1_CLK_ENABLE();
	__HAL_RCC_GPIOA_CLK_ENABLE();

	/*
	 * MISO ---> PA6
	 * MOSI ---> PA7
	 * CLK  ---> PA5
	 */
	tSPIGpio.Pin = (GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7);
	tSPIGpio.Mode = GPIO_MODE_AF_PP;
	tSPIGpio.Alternate = GPIO_AF5_SPI1;
	tSPIGpio.Pull = GPIO_NOPULL;
	tSPIGpio.Speed = GPIO_SPEED_FREQ_VERY_HIGH;

	HAL_GPIO_Init(GPIOA, &tSPIGpio);

	/* Configure SPI Module*/
	tSpi1.Instance = SPI1;
	tSpi1.Init.Mode = SPI_MODE_MASTER;
	tSpi1.Init.Direction = SPI_DIRECTION_2LINES;
	tSpi1.Init.DataSize = SPI_DATASIZE_8BIT;
	tSpi1.Init.CLKPolarity = SPI_POLARITY_LOW;
	tSpi1.Init.CLKPhase = SPI_PHASE_1EDGE;
	tSpi1.Init.NSS = SPI_NSS_SOFT;
	tSpi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_8;
	tSpi1.Init.FirstBit = SPI_FIRSTBIT_MSB;
	tSpi1.Init.TIMode = SPI_TIMODE_DISABLE;
	tSpi1.Init.CRCCalculation = SPI_CRCCALCULATION_DISABLE;

	HAL_SPI_Init(&tSpi1);
}

void SysTick_Handler(void)
{
	HAL_IncTick();
}
